name: My First GitHub Actions

on: [push]

jobs:
  build:
    runs-on: ${{ matrix.os-platforms}}

    strategy:
      matrix:
        os-platforms: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py


    - name: Notify Slack on Failure
      if: failure()  # This ensures the step ONLY runs if a previous step failed
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_COLOR: '#ff0000'
        SLACK_MESSAGE: "CI Pipeline Failed on ${{ matrix.os-platforms }} for Python ${{ matrix.python-version }}! ❌"
        SLACK_TITLE: "Build Failure Alert"
