name: My First GitHub Actions

on: [push]

jobs:
  test-logic:
    runs-on: ${{ matrix.os-platforms}}

    strategy:
      matrix:
        os-platforms: [ubuntu-latest, macos-latest]
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest
        # You MUST include flake8 here so the Runner has the tool!
        pip install pytest flake8 pytest-cov flask

    - name: Lint with flake8
      run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. 
          # For your "Catch", change this to fail on errors later!
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Run tests
      run: |
        cd src
        python -m pytest addition.py


    # - name: Notify Slack on Failure
    #  if: failure()  # This ensures the step ONLY runs if a previous step failed
    #  uses: rtCamp/action-slack-notify@v2
    #  env:
    #    SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    #    SLACK_COLOR: '#ff0000'
    #    SLACK_MESSAGE: "CI Pipeline Failed on ${{ matrix.os-platforms }} for Python ${{ matrix.python-version }}! ❌"
    #    SLACK_TITLE: "Build Failure Alert"

    - name: Personal Failure Alert
      if: failure()
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_TITLE: "Hey @${{ github.actor }}, your build failed! ❌"
        SLACK_COLOR: '#FF0000'
        # This <@ID> format is the only way to trigger a "Mobile Ping" in Slack
        SLACK_MESSAGE: |
          *Actor:* ${{ github.actor }}
          *Branch:* ${{ github.ref_name }}
          *Attention:* <@${{ secrets.SLACK_MEMBER_ID }}> - Please check your latest commit!


# CD Part of this pipeline
  build-and-push:
    needs: test-logic # <--- This is the "Magic" bridge to CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build Docker Image
        # We tag it with the 'sha' (unique commit ID) for versioning
        run: docker build -t my-python-app:${{ github.sha }} .

      - name: Log Image Status
        run: echo "Image successfully built and ready for registry!"

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          
          tags: devopsmeghss/my-python-app:latest
